### ISSUE TITLE
Updated examples...

### ISSUE THREAD

**Issue by JakeHartnell** [whitebox-labs/grow-iot-atlas#1]
Saw this in my notifications and then realized the examples were out of date. I've updated them on the wiki! https://github.com/CommonGarden/Grow-IoT/wiki

For a full Raspberry pi example checkout Grow-Hub and comment out anything you don't need: https://github.com/CommonGarden/Grow-Hub/blob/development/grow-hub.js

When I get the T3 I'll make a cleaner example. ; )

**Comment by JakeHartnell** [comment]
Also added temperature probe example: https://github.com/CommonGarden/Grow-IoT/wiki/Atlas-Scientific-Temperature

**Comment by extrapixel** [comment]
thx :) is this up to date? https://github.com/CommonGarden/Grow-IoT/wiki/Raspberry-Pi

**Comment by JakeHartnell** [comment]
Mostly, I updated it with information about connecting to a Grow-IoT instance. Open an issue on Grow-IoT if you run into problems.
